function doc = toLatexDoc(latex)

doc = ['\documentclass{article}' char(10) ...
    '\usepackage[T1]{fontenc}' char(10) ...
    '\usepackage{graphicx}' char(10) ...
    '\usepackage{fancyhdr}' char(10) ...
    '\usepackage{amsmath}' char(10) ...
    '\usepackage{fancybox}' char(10) ...
    '\usepackage{hyperref}' char(10) ...
    '\usepackage{pbox}' char(10) ...
    '\usepackage{float}' char(10) ...
    '\usepackage{color}' char(10) ...
    '\usepackage{ifthen}' char(10) ...
    '\begin{document}' char(10) ...
    latex char(10) ...
    '\end{document}'];